export const initialNodes = [
  {
    id: "1-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=python&theme=light" },
    position: { x: 50, y: 50 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [
      "My Main Stack",
      "Backend Stack",
      "DevOps Stack",
      "AI/ML Solutions",
    ],
  },
  {
    id: "2-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=ts&theme=light" },
    position: { x: 50, y: 150 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack", "Frontend Stack", "Backend Stack"],
  },
  {
    id: "3-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=c&theme=light" },
    position: { x: 150, y: 50 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My OS favorites tools"],
  },
  {
    id: "4-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=cpp&theme=light" },
    position: { x: 150, y: 150 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My OS favorites tools"],
  },
  {
    id: "5-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=js&theme=light" },
    position: { x: 250, y: 50 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "6-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=html&theme=light" },
    position: { x: 250, y: 150 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "7-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=css&theme=light" },
    position: { x: 350, y: 50 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },

  {
    id: "8-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=go&theme=light" },
    position: { x: 350, y: 150 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Backend Stack"],
  },
  {
    id: "9-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=java&theme=light" },
    position: { x: 450, y: 50 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "10-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=rust&theme=light" },
    position: { x: 450, y: 150 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My OS favorites tools"],
  },
  {
    id: "11-Languages",
    data: { imageUrl: "https://skillicons.dev/icons?i=bash&theme=light" },
    position: { x: 550, y: 150 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["DevOps Stack", "My OS favorites tools"],
  },
  {
    id: "1-Frameworks",
    data: { imageUrl: "https://skillicons.dev/icons?i=react&theme=light" },
    position: { x: 700, y: 50 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack", "Frontend Stack"],
  },
  {
    id: "2-Frameworks",
    data: { imageUrl: "https://skillicons.dev/icons?i=nextjs&theme=light" },
    position: { x: 800, y: 50 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack", "Frontend Stack"],
  },
  {
    id: "3-Frameworks",
    data: { imageUrl: "https://skillicons.dev/icons?i=vue&theme=light" },
    position: { x: 900, y: 50 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },

  {
    id: "4-Frameworks",
    data: { imageUrl: "https://skillicons.dev/icons?i=nestjs&theme=light" },
    position: { x: 800, y: 150 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Backend Stack"],
  },
  {
    id: "5-Frameworks",
    data: { imageUrl: "https://skillicons.dev/icons?i=nodejs&theme=light" },
    position: { x: 700, y: 150 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Backend Stack"],
  },
  {
    id: "6-Frameworks",
    data: { imageUrl: "https://skillicons.dev/icons?i=express&theme=light" },
    position: { x: 1000, y: 150 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "7-Frameworks",
    data: { imageUrl: "https://skillicons.dev/icons?i=django&theme=light" },
    position: { x: 900, y: 150 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack", "Backend Stack"],
  },
  {
    id: "8-Frameworks",
    data: { imageUrl: "https://skillicons.dev/icons?i=flask&theme=light" },
    position: { x: 1000, y: 50 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Backend Stack"],
  },
  {
    id: "1-Styles",
    data: { imageUrl: "https://skillicons.dev/icons?i=bootstrap&theme=light" },
    position: { x: 50, y: 350 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "2-Styles",
    data: { imageUrl: "https://skillicons.dev/icons?i=tailwind&theme=light" },
    position: { x: 150, y: 350 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Frontend Stack"],
  },
  {
    id: "3-Styles",
    data: { imageUrl: "https://skillicons.dev/icons?i=sass&theme=light" },
    position: { x: 50, y: 450 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack", "Frontend Stack"],
  },
  {
    id: "4-Styles",
    data: { imageUrl: "https://skillicons.dev/icons?i=materialui&theme=light" },
    position: { x: 150, y: 450 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Frontend Stack"],
  },
  {
    id: "1-Cloud",
    data: { imageUrl: "https://skillicons.dev/icons?i=docker&theme=light" },
    position: { x: 650, y: 350 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["DevOps Stack"],
  },
  {
    id: "2-Cloud",
    data: { imageUrl: "https://skillicons.dev/icons?i=aws&theme=light" },
    position: { x: 750, y: 350 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack", "DevOps Stack", "AI/ML Solutions"],
  },
  {
    id: "3-Cloud",
    data: { imageUrl: "https://skillicons.dev/icons?i=firebase&theme=light" },
    position: { x: 850, y: 350 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Backend Stack"],
  },
  {
    id: "4-Cloud",
    data: { imageUrl: "https://skillicons.dev/icons?i=nginx&theme=light" },
    position: { x: 950, y: 350 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack", "DevOps Stack"],
  },
  {
    id: "5-Cloud",
    data: { imageUrl: "https://skillicons.dev/icons?i=kafka&theme=light" },
    position: { x: 650, y: 450 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Backend Stack"],
  },
  {
    id: "6-Cloud",
    data: { imageUrl: "https://skillicons.dev/icons?i=kubernetes&theme=light" },
    position: { x: 750, y: 450 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["DevOps Stack"],
  },
  {
    id: "7-Cloud",
    data: { imageUrl: "https://skillicons.dev/icons?i=rabbitmq&theme=light" },
    position: { x: 850, y: 450 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "8-Cloud",
    data: {
      imageUrl: "https://skillicons.dev/icons?i=githubactions&theme=light",
    },
    position: { x: 950, y: 450 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["DevOps Stack"],
  },
  {
    id: "9-Cloud",
    data: { imageUrl: "https://skillicons.dev/icons?i=linux&theme=light" },
    position: { x: 1050, y: 450 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack", "My OS favorites tools"],
  },
  {
    id: "1-Tools",
    data: { imageUrl: "https://skillicons.dev/icons?i=redux&theme=light" },
    position: { x: 50, y: 650 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "2-Tools",
    data: { imageUrl: "https://skillicons.dev/icons?i=graphql&theme=light" },
    position: { x: 150, y: 650 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Backend Stack"],
  },
  {
    id: "3-Tools",
    data: { imageUrl: "https://skillicons.dev/icons?i=jest&theme=light" },
    position: { x: 250, y: 650 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["DevOps Stack"],
  },
  {
    id: "4-Tools",
    data: { imageUrl: "https://skillicons.dev/icons?i=figma&theme=light" },
    position: { x: 350, y: 650 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "5-Tools",
    data: { imageUrl: "https://skillicons.dev/icons?i=git&theme=light" },
    position: { x: 50, y: 750 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["DevOps Stack"],
  },
  {
    id: "6-Tools",
    data: { imageUrl: "https://skillicons.dev/icons?i=github&theme=light" },
    position: { x: 150, y: 750 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["DevOps Stack"],
  },
  {
    id: "7-Tools",
    data: { imageUrl: "https://skillicons.dev/icons?i=postman&theme=light" },
    position: { x: 250, y: 750 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Backend Stack"],
  },
  {
    id: "8-Tools",
    data: { imageUrl: "https://skillicons.dev/icons?i=webpack&theme=light" },
    position: { x: 350, y: 750 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "9-Tools",
    data: { imageUrl: "https://skillicons.dev/icons?i=wordpress&theme=light" },
    position: { x: 450, y: 750 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "1-Database",
    data: { imageUrl: "https://skillicons.dev/icons?i=prisma&theme=light" },
    position: { x: 350, y: 350 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["Backend Stack"],
  },
  {
    id: "2-Database",
    data: { imageUrl: "https://skillicons.dev/icons?i=mongodb&theme=light" },
    position: { x: 450, y: 350 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "3-Database",
    data: { imageUrl: "https://skillicons.dev/icons?i=postgres&theme=light" },
    position: { x: 350, y: 450 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack", "Backend Stack"],
  },
  {
    id: "4-Database",
    data: { imageUrl: "https://skillicons.dev/icons?i=redis&theme=light" },
    position: { x: 450, y: 450 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack", "Backend Stack", "AI/ML Solutions"],
  },
  {
    id: "1-Destop",
    data: { imageUrl: "https://skillicons.dev/icons?i=qt&theme=light" },
    position: { x: 650, y: 650 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["My Main Stack"],
  },
  {
    id: "2-Destop",
    data: { imageUrl: "https://skillicons.dev/icons?i=tauri&theme=light" },
    position: { x: 650, y: 750 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: [],
  },
  {
    id: "1-IA",
    data: { imageUrl: "https://skillicons.dev/icons?i=tensorflow&theme=light" },
    position: { x: 900, y: 650 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["AI/ML Solutions"],
  },
  {
    id: "2-IA",
    data: { imageUrl: "https://skillicons.dev/icons?i=opencv&theme=light" },
    position: { x: 900, y: 750 },
    type: "imageNode",
    style: {
      background: "#1e293b",
      color: "#fff",
      padding: "4px",
      borderRadius: "10px",
    },
    categories: ["AI/ML Solutions"],
  },
  {
    id: "1-group",
    data: { label: "Programming languages" },
    position: { x: 30, y: 30 },
    type: "group",
    style: {
      opacity: 0.3,
      borderRadius: "10px",
      width: 600,
      height: 200,
    },
    categories: ["group"],
  },
  {
    id: "2-group",
    data: { label: "Frameworks Web" },
    position: { x: 680, y: 30 },
    type: "group",
    style: {
      opacity: 0.3,
      borderRadius: "10px",
      width: 400,
      height: 200,
    },
    categories: ["group"],
  },
  {
    id: "3-group",
    data: { label: "Frameworks Web" },
    position: { x: 30, y: 330 },
    type: "group",
    style: {
      opacity: 0.3,
      borderRadius: "10px",
      width: 200,
      height: 200,
    },
    categories: ["group"],
  },
  {
    id: "4-group",
    data: { label: "Frameworks Web" },
    position: { x: 330, y: 330 },
    type: "group",
    style: {
      opacity: 0.3,
      borderRadius: "10px",
      width: 200,
      height: 200,
    },
    categories: ["group"],
  },
  {
    id: "5-group",
    data: { label: "Frameworks Web" },
    position: { x: 630, y: 330 },
    type: "group",
    style: {
      opacity: 0.3,
      borderRadius: "10px",
      width: 500,
      height: 200,
    },
    categories: ["group"],
  },
  {
    id: "6-group",
    data: { label: "Frameworks Web" },
    position: { x: 30, y: 630 },
    type: "group",
    style: {
      opacity: 0.3,
      borderRadius: "10px",
      width: 500,
      height: 200,
    },
    categories: ["group"],
  },
  {
    id: "7-group",
    data: { label: "Frameworks Web" },
    position: { x: 630, y: 630 },
    type: "group",
    style: {
      opacity: 0.3,
      borderRadius: "10px",
      width: 100,
      height: 200,
    },
    categories: ["group"],
  },
  {
    id: "8-group",
    data: { label: "Frameworks Web" },
    position: { x: 880, y: 630 },
    type: "group",
    style: {
      opacity: 0.3,
      borderRadius: "10px",
      width: 100,
      height: 200,
    },
    categories: ["group"],
  },
];
